version: '3.9'

services:
  flask:
    build: .
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: postgres:latest
    volumes:
       - postgres_data:/var/lib/postgresql/data
    restart: always
    expose:
      - "5432"
  adminer:
    image: adminer
    restart: always
volumes:
  postgres_data: